-- Intentionally contains no users, passwords, aliases, tokens, or product data.
-- The identity migration installs a synthetic, non-blocking local compatibility row.
-- Synthetic Auth users used by tests are transaction-scoped in pgTAP fixtures.
